### ISSUE TITLE
code-llama-7b-python精度对不上

### ISSUE THREAD

**Issue by Connor-Shen** [FlagOpen/TACO#5]
我尝试了test split中easy部分的200题，跑了一遍测得的pass@1只有3左右，和paper里的精度不符。
我已经使用了repo中的prompt和evaluation部分，设置n_samples=1，temperature=0.8。
想求助原因，非常感谢！

**Comment by rongaoli** [comment]
Due to the complexity of the Code Challenge, fine-tuning the model is necessary, as discussed in Alphacode paper. We fine-tuned several state-of-the-art coding models on the TACO dataset, which are now available on Hugging Face. Please check them at: https://huggingface.co/FlagOpen @kartikzheng @Connor-Shen

**Comment by kartikzheng** [comment]
> Due to the complexity of the Code Challenge, fine-tuning the model is necessary, as discussed in Alphacode paper. We fine-tuned several state-of-the-art coding models on the TACO dataset, which are now available on Hugging Face. Please check them at: https://huggingface.co/FlagOpen由于代码挑战的复杂性，对模型进行微调是必要的，正如 Alphacode 论文中所讨论的那样。我们在 TACO 数据集上微调了几个最先进的编码模型，这些模型现在可以在 Hugging Face 上使用。请在以下位置查看： https://huggingface.co/FlagOpen @kartikzheng @Connor-Shen

Okay, thank you.
