### ISSUE TITLE
数据污染问题

### ISSUE THREAD

**Issue by Ezra-Yu** [FlagOpen/TACO#6]
你们的工作太棒了！ TACO 是目前看到的开源数据集中，最棒的代码生成数据集。

比较好奇你们在制作数据集时，有没有考虑到**数据污染**问题。在LLM的时代，测试集是否被污染是一个非常重要的参考点。
我在里面论文里没有找到相关的信息。

**Comment by rongaoli** [comment]
Hello!

Thank you for your kind words and insightful question. 

Data contamination is indeed a significant concern, and we are actively seeking solutions. Using recent problems as a test set might hinder the evaluation of newest model and not provide a comprehensive evaluation due to potential scarcity in certain algorithm categories. In our future work with TACO, we aim to mitigate this issue, ensuring that our dataset remains a reliable benchmark for evaluating both current and future models. 

Please stay tuned for our updates, and we appreciate your interest in the quality of our dataset :)

**Comment by rongaoli** [comment]
> 你们的工作太棒了！ TACO 是目前看到的开源数据集中，最棒的代码生成数据集。
> 
> 比较好奇你们在制作数据集时，有没有考虑到**数据污染**问题。在LLM的时代，测试集是否被污染是一个非常重要的参考点。 我在里面论文里没有找到相关的信息。

Hello!

Thank you for your kind words and insightful question.

Data contamination is indeed a significant concern, and we are actively seeking solutions. Using recent problems as a test set might hinder the evaluation of newest model and not provide a comprehensive evaluation due to potential scarcity in certain algorithm categories. In our future work with TACO, we aim to mitigate this issue, ensuring that our dataset remains a reliable benchmark for evaluating both current and future models.

Please stay tuned for our updates, and we appreciate your interest in the quality of our dataset :)
