### ISSUE TITLE
Finetuned Models

### ISSUE THREAD

**Issue by abwilf** [FlagOpen/TACO#9]
Hello! I'm having some trouble reproducing the finetuning with the script – would you mind releasing the trained models so I can verify their evaluation results and build on top of them? Thank you!

**Comment by rongaoli** [comment]
> Hello! I'm having some trouble reproducing the finetuning with the script – would you mind releasing the trained models so I can verify their evaluation results and build on top of them? Thank you!

Hi

Thanks for your interest in our work. We are working on uploading the finetuned models.

We expect to upload the following TACO fine-tuned versions of models by next week at the earliest:

- Starcoder-15B
- Starcoder-1B
- CodeLlama-7b-python
- CodeGen25-mono

The upload process will take some time due to the large size of the model weights. We will complete the upload as soon as possible and notify you.

**Comment by rongaoli** [comment]
Hello world! We're excited to announce that all models from our TACO research are now available on 🤗Hugging Face! You can download our SFT models from the following link: https://huggingface.co/FlagOpen. Please note that our models have been trained solely on the training split of the TACO dataset.

**Comment by rongaoli** [comment]
@abwilf
